### ISSUE TITLE
Archive rom launcher.

### ISSUE THREAD

**Issue by italian0520** [zach-morris/plugin.program.iarl#11]
After following step by step instructions kodi will not launch the games. It says it's working then does nothing.

**Comment by zach-morris** [comment]
Turn on debug logging and kodi, then provide a log

**Comment by italian0520** [comment]
The game downloads but will not play. I have turned on the debug logging
and it's still not working. Do I still need to download retroarch? And if I
do can download on my kodi or do I have to download on mac?

**Comment by zach-morris** [comment]
The [wiki](https://github.com/zach-morris/plugin.program.iarl/wiki/2.--IARL-Setup-Tutorial) provides all the steps required to set this up.

The [FAQ](https://github.com/zach-morris/plugin.program.iarl/wiki/5.--FAQ#13-game-xyz-does-not-work-your-addon-is-broken) provides answers to common questions people have.

If you've followed the steps in the wiki, it should work.  My guess is you have not followed the setup instructions.
