### ISSUE TITLE
Missing a specific rom

### ISSUE THREAD

**Issue by Cozmikaos** [zach-morris/plugin.program.iarl#12]
Hello Zach ,

Firstly, thank you so much for the IARL, you rock and are legend. 

Secondly i was wondering where the IARL pulled its roms from because there was one certain rom and im not certain if anymore that is missing

Namely the "Turrican" series. Cannot for the life of me find super turrican or super turrican 2 or mega turrican. 

Thank you

**Comment by zach-morris** [comment]
I've personally included several archives from the internet archive as defaults for IARL. I've filtered the full list of available games from the internet archive to try and adhere to a "one game/one file" type mentality, but sometime my filtering isn't perfect.  The addon also provides full unfiltered lists of archives where applicable, see [here](https://github.com/zach-morris/plugin.program.iarl/wiki/5.--FAQ#9--whatwhere-are-the-unfiltered-games-lists).  A quick search shows some of the games you were interested in are in those lists.

Happy gaming
