### ISSUE TITLE
OSMC?

### ISSUE THREAD

**Issue by trevevs** [zach-morris/plugin.program.iarl#13]
allo
Any chance of a guide to install this with OSMC pls?  retrosmc?
thanks million

**Comment by zach-morris** [comment]
Not at this time.   It looks like Retrosmc just installs retropie which isn't currently supported.  Not sure if [Gamestarter](http://forum.kodi.tv/showthread.php?tid=276002) supports OSMC?  Gamestarter is essentially the same thing as retrosmc it appears.  If Gamestarter works, then IARL should work.
