### ISSUE TITLE
Plugin is attempting to load save state instead of rom

### ISSUE THREAD

**Issue by GentlemanJ** [zach-morris/plugin.program.iarl#18]
When using Retroarch with auto save states enabled, IARL is passing the filename of the auto save state instead of that of the rom to RetroArch.  RetroArch does not support loading of roms this way. 

Log attached:

IARL:  Download started for 20.  Final Fantasy
IARL:  Matching files found for /home/<user>/ROMS/NES/Final Fantasy (USA).zip: /home/<user>/ROMS/NES/Final Fantasy (U).state.auto, /home/<user>/ROMS/NES/Final Fantasy (U).nes, /home/<user>/ROMS/NES/Final Fantasy (U).state
IARL:  File was found to exist locally, no overwrite option selected
IARL:  Matching file that already exists: /home/<user>/ROMS/NES/Final Fantasy (U).state.auto
IARL:  File was not recognized as a zipfile and not extracted, pointing back to file: /home/<user>/ROMS/NES/Final Fantasy (U).state.auto
IARL:  External launch command sent: "/usr/bin/retroarch"  -L /usr/lib/libretro/nestopia_libretro.so "/home/<user>/ROMS/NES/Final Fantasy (U).state.auto"

**Comment by zach-morris** [comment]
Thanks for the report.  I do have the addon look for savestates and ignore them (see [here](https://github.com/zach-morris/plugin.program.iarl/blob/master/resources/lib/util.py#L2600)), but looks like I forgot a few extension types.   I'll fix this in the next update.

Any other savestate filetypes that you know of let me know.

**Comment by zach-morris** [comment]
Added additional save states to the ignore list with [this](https://github.com/zach-morris/plugin.program.iarl/commit/624af8ec190894c8dc1aefc3aa321d953e7be297) commit
