### ISSUE TITLE
Windows custom download path = URL

### ISSUE THREAD

**Issue by B-V-** [zach-morris/plugin.program.iarl#20]
When changing the download path to custom it starts with a URL, in my case it is HTTP://SRP.NU/ (SuperRepo)

Within these settings it is not possible to get a location on the disk.

I'm using a Windows platform, think that is the problem. 

Manually editing each archive XML file, value "emu_downloadpath" works but that option is not for everyone. 

Is it possible to fix this in future update, for all the windows users among us that have no XML knowledge? ;)

**Comment by zach-morris** [comment]
I'm not sure I understand the request.  You want to download to an http location?  Thats not possible.  Download locations currently only support local disks.

**Comment by B-V-** [comment]
I would like to save the Roms on my local disk, the way you describe in your wiki-setup page. But when I change the download path from default to custom and the poppup I get afterwards starts with an URL and not with my local disk. 

I added an picture of the problem, hope that explains it.

![img_20170102_225156](https://cloud.githubusercontent.com/assets/6977812/21596654/1cf45196-d13e-11e6-946c-0feccfa8ff5b.jpg)

**Comment by zach-morris** [comment]
Ok, thanks for the clarification.
The behavior is definitely weird...  This is not normal.  The addon usually just opens a dialog with the 'default' local file path shown.  Should be the same path you see when you just go to the file browser within Kodi.  Perhaps you don't have a default path setup yet? or theres some weird advance setting thats causing it to choose that location?

**Comment by B-V-** [comment]
File manager can access my filesystem, but I found a solution. I added a new source r5
