### ISSUE TITLE
Local ROM zipped files

### ISSUE THREAD

**Issue by waltwhitman6969** [zach-morris/plugin.program.iarl#21]
Is it normal for IARL to unzip my zipped folders that have the games in them when I launch them?

For example, had 007 Golden Eye (N64) in a zipped folder. As soon as I launched 007 from IARL for the first time, it unzipped that folder, placed the game in the directory, and deleted the zipped folder.

**Comment by zach-morris** [comment]
Yes, by default the game will be unzipped.  This was originally in place to support Retroplayer, which required the game to be unzipped.  That may change, so the default could change as well.  The user can manually change that by editing the game xml file and change:
`<emu_postdlaction>unzip_rom</emu_postdlaction>`
to
`<emu_postdlaction>none</emu_postdlaction>`

Keep in mind though, that whatever core / emulator you're trying to use must support zipped rom files
