### ISSUE TITLE
I can't get the SNES to open the game file list. The other systems work fine... 

### ISSUE THREAD

**Issue by jared3870** [zach-morris/plugin.program.iarl#22]

**Comment by zach-morris** [comment]
Please provide a debug log if you think you've found a bug.  SNES is working for me and others though.

**Comment by jared3870** [comment]
https://paste.ubuntu.com/23788934

**Comment by zach-morris** [comment]
Thanks for the log.  My best guess is the xml file is corrupted for some reason.  You can replace it by deleting the file in the folder /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.program.iarl/dat_files

And replacing it with the one from github [here](https://github.com/zach-morris/plugin.program.iarl/tree/master/resources/data/dat_files).  Or you can delete the entire folder
/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.program.iarl

and try re-installing the addon.

Long term fix for this issue:  I can probably update my addon to tell the user something is wrong and ask them if they want to try and delete the file.
