### ISSUE TITLE
System/BIOS Directory default value in documentation

### ISSUE THREAD

**Issue by kdejaeger** [zach-morris/plugin.program.iarl#23]
I just discovered this project, which is awsome. Since I don't want to download 2TB of roms on nvidia shield ;).

I have a question about 'System/BIOS Directory' on the wiki page: https://github.com/zach-morris/plugin.program.iarl/wiki/1.--Setup#basic-setup-instructions .

By default in android, it shows `<Content dir>`. Does this mean that it still needs to be configured to it's own directory or can we than leave that as-is?

**Comment by zach-morris** [comment]
<content dir>, as far as I know, is the same directory your rom files are.  So, if say you set the MAME archive to save to:
/sdcard/games/arcade/

IARL will try and save the files and launch the game from that location.
Then Retroarch will look for all the game files / bios files / hash files / etc in that folder, so in IARL, you'd have to set 'System/BIOS Directory' to /sdcard/games/arcade/.

They key is that they match.

This setting is currently only used for MAME/MESS, which requires hash files to be present (IARL downloads them and puts them into the Retroarch system/bios directory).  If you don't care about the MAME/MESS games, then you can leave the setting blank and play away.

**Comment by kdejaeger** [comment]
Aren't all games downloaded by IARL through the internet archive in a temp Kodi folder?

**Comment by zach-morris** [comment]
By default yes.
You can change that on a per archive basis though if you choose.  See [here](https://github.com/zach-morris/plugin.program.iarl/wiki/2.--Addon-Settings#game-archive-xml-settings).

Technically, you could set 'System/BIOS Directory' to the temp IARL directory.  The problem with that though is BIOS files.  Many systems need BIOS files to function, which you the user have to provide.  BIOS requirements for each retroarch core are listed in the Retroarch [wiki](https://wiki.libretro.com/index.php?title=Main_Page).  If you put your BIOS files in the temp IARL folder, they would eventually be deleted when the cache folder is full.

Easiest solution:
- Change the Retroarch setting for System/BIOS directory to a folder of your choosing
- Put all the BIOS files you need in that folder.  If you're good at google, you can find a pre-configured BIOS folder with everything you need already.
 - Change the IARL setting to match what you set in Retroarch

**Comment by kdejaeger** [comment]
Ok, I see. So a 'MAME' game needs an emulator, a ROM and sometimes a BIOS. Starting to understand this. Why are those BIOS files not bundled with the internet archive roms?

**Comment by zach-morris** [comment]
BIOS files are kind of taboo, mainly for legal reasons.  It would be trivial to include them, but they aren't for that reason.
https://www.reddit.com/r/emulation/comments/1xuduj/what_is_a_bios/
