### ISSUE TITLE
"Infinite" post_download_action operation

### ISSUE THREAD

**Issue by NerdFlix** [zach-morris/plugin.program.iarl#25]
Hi Zach, firstly I'd like to thank you for this awesome addon, you're doing a pretty good job for the community. This "bug" doesn't generate any log(I mean clarifying what is wrong) or warning/error message, just keeps its operation for a long long time until it stops and nothing happens, as my english is not that good I'll provide some code details(please keep in mind that I'm not a coder).
Inside the function **download_rom_only(iarl_data)** in **addon.py*, line 1057(#1.  Check temp folder and clean if necessary) you check if temp folder is set to 'default', and clean it if needed, and in line 1061(#2.  Check if filename(s) already exist) you check to see if it should ask to overwrite or keep existing roms files.
If my **emu_postdlaction**(Playstation 1 archive) is for example **convert_7z_m3u** and this emu_postdlaction has already happened before for the current rom, the convert_7z_m3u operation takes too long time and nothing happens(The operation is not done), no log file, and no warning/error message is shown, so I put some code between steps (#1.  Check temp folder and clean if necessary) and (#2.  Check if filename(s) already exist), it solved the "problem" to me, I dont know if it happens to everybody else, I'm not using 'Default' temp folder for my roms download. Again thanks for the hard work, we really like your work, and sorry for this long message, I just wanted to be as clear as possible with my issue. This is my ungly code that solve it to me:

    #1.  Check temp folder and clean if necessary
    if 'default' in iarl_data['current_archive_data']['emu_download_path']:
        check_temp_folder_and_clean(iarl_data['settings']['download_cache'])
		
		
	############################  MODIFIED #############################################################################################			
	#1.1.  Delete converted/unziped rom folder to avoid infinite post_download_action operation 
    else:		
		current_dl_path			= iarl_data['current_archive_data']['emu_download_path']		
		un7zip_folder_name 		= clean_file_folder_name(iarl_data['current_rom_data']['rom_title'])		
		current_path_to_delete	= os.path.join(current_dl_path,un7zip_folder_name)
		if(os.path.isdir(current_path_to_delete)):
			shutil.rmtree(current_path_to_delete) #If it exists, delete it

############################  MODIFIED #############################################################################################
#2.  Check if filename(s) already exist
...

**Comment by zach-morris** [comment]
Thanks for this info.  If I understand correctly, the issue you're having is with a game that already exists on your system, but fails to load?

The post download function your referring to [convert_7z_m3u](https://github.com/zach-morris/plugin.program.iarl/blob/master/resources/lib/util.py#L2413), should look to see if the game folder and m3u file already exist.  If it fails, the error is most likely in that code.  Could you post a debug log?

**Comment by NerdFlix** [comment]
Never mind I updated your addon and I think the issue is gone. I will maintain the lazy solution just in case, that always delete the folder where .m3u is. Thanks for everything

**Comment by zach-morris** [comment]
There was an issue with that previously that I think was fixed in an update.  I recall the error was just not identifying the previously created game folder.  Should work and not require any modifications, so if you find the issue again just re-open another issue.
