### ISSUE TITLE
ImportError: No module named resources.lib.webutils

### ISSUE THREAD

**Issue by jdig4240** [zach-morris/plugin.program.iarl#29]
After 1.6.1 update, broke my setup on Android and Windows. Will not let me set it up and run the wizard. I even started with a fresh install of Kodi with only your Repo. Installed only IARL from repo and attempted to set up Retroarch app location, and system folder, tried running Setup wizard and errors out. This log shows everything from fresh start, installing repo, Installing IARL, then attempting to use the Setup wizard, no luck. Everything was running fine before the update on both Android and my Windows setup, now nothing.

Kodi Log: http://jed.one/Other%20stuff/kodiIARL.log

ImportError: No module named resources.lib.webutils

**Comment by zach-morris** [comment]
Bummer, looks like a typo.  I've pushed a fix to github
https://github.com/zach-morris/plugin.program.iarl/commit/4eef08ba1814a1ce618cad3c87f3911119e2ad34

**Comment by jdig4240** [comment]
Another quick fix by the man! I confirm the fix works, thanks again Zach

**Comment by zach-morris** [comment]
Thanks for verifying.  1.6.2 is available now with the fix
