### ISSUE TITLE
A lot of 404 errors related to FBA

### ISSUE THREAD

**Issue by Piehr** [zach-morris/plugin.program.iarl#31]
Hello,

First, thanks a lot for this incredible plugin :)

Since this morning, it seems that a lot of roms are not downloading anymore. At least, everyone located in the FBA entry, resulting on 37kb zip files.

Roms are located here: fba029739SplitArcadeOnly_201612/fba029739SplitArcadeOnly.zip/ROMNAME.zip

Some others may be unavailable too, didn't check.

Do you know what's happening and how to resolve this issue? Thanks!

Best regards,

Piehr

**Comment by zach-morris** [comment]
Thanks.  Looks like the archive changed.  I'll see if I can update that.

**Comment by zach-morris** [comment]
Updated with [this](https://github.com/zach-morris/plugin.program.iarl/commit/3a86cef1ea881a0c0a579f2976c6c2d9af493e13) change

**Comment by Piehr** [comment]
Thanks a lot, that's great!
