### ISSUE TITLE
Nintendo DS and PS2 games Enhancement

### ISSUE THREAD

**Issue by NerdFlix** [zach-morris/plugin.program.iarl#42]
Hi Zach, 
I think you already know this, but just in case, there are collections of Nintendo DS and PS2 on Archive.org, I think both consoles could be a good enhancement to IARL, what do you think?
I've already scraped their lists from TheGamesDB (images and videos), let me know if you want them.

Links:https://archive.org/download/NoIntroNintendoDsNumberedDecrypted

https://archive.org/details/RedumpSonyPS2NTSCU

https://archive.org/details/RedumpSonyPS2NTSCUPart2

**Comment by zach-morris** [comment]
Thanks for the links, but I will probably not add these archives for the time being.  That being said, others of course can add whatever lists they want to the addon after installation.

**Comment by NerdFlix** [comment]
Ok Zach, thanks for answering
