### ISSUE TITLE
Error in files when running wizard on slower machines

### ISSUE THREAD

**Issue by sublinhado** [zach-morris/plugin.program.iarl#44]
Setup Wizard configured the wrong core for the 3DO platform.
System: Android
Expected core: 4DO
Configured core: vice_x64

Updating external launcher to 4DO works as expected

**Comment by zach-morris** [comment]
Hmm...  I'm not immediately seeing an issue with how i have it coded (see [here](https://github.com/zach-morris/plugin.program.iarl/blob/master/resources/lib/run_iarl_wizard.py#L744)).

Can you provide a debug log?

**Comment by sublinhado** [comment]
Here is a log for running the Wizard and than updating the ext loader manually to 4DO.
[kodi.log.txt](https://github.com/zach-morris/plugin.program.iarl/files/1236309/kodi.log.txt)

**Comment by zach-morris** [comment]
Well, that looks confusing to me.  You're updating C64 to launch with 4DO:
```
08:29:23.018 T:1888549152  NOTICE: [resources.lib.xbmcswift2b] Request for "/update_xml/%2Fstorage%2Femulated%2F0%2FAndroid%2Fdata%2Forg.xbmc.kodi%2Ffiles%2F.kodi%2Fuserdata%2Faddon_data%2Fplugin.program.iarl%2Fdat_files%2FC64_ZachMorris.xml" matches rule for function "update_xml_value"
08:29:23.019 T:1888549152   DEBUG: IARL:  Updating external launch command for: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.program.iarl/dat_files/C64_ZachMorris.xml
08:29:28.576 T:1888549152   DEBUG: IARL:  New External Launch Command is /system/bin/am start --user 0 -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -e ROM "%ROM_PATH%" -e LIBRETRO /data/data/com.retroarch/cores/4do_libretro_android.so -e CONFIGFILE %CFG_PATH% -e IME com.android.inputmethod.latin/.LatinIME -n com.retroarch/.browser.retroactivity.RetroActivityFuture
```

Looking at the xml files, C64 is correct and 3DO is correct, so it's not like the filenames are swapped.  I'm not sure I understand from the logs what the error is, or how things got confused.  I tried this on my end, both with the wizard and manually and the correct files are updated when the commands are run.

From the logs and from what you're saying it appears the files are getting confused somehow, but I can't see how thats happening.  Did you manually add them somehow and rename the files?

**Comment by sublinhado** [comment]
After your last problem, I started from a clean install and noticed that when you run the wizard there is some seconds delay until the progress pop-up is displayed. If in the mean time you press the Run Wizard button more than once the data files may to mix up.

**Comment by zach-morris** [comment]
OK, that sort of makes sense.  I'll see if there's a way to prevent that.
