### ISSUE TITLE
Problem with FBA ando Mame 2014

### ISSUE THREAD

**Issue by langostaman** [zach-morris/plugin.program.iarl#46]
Hi!!
Fiesta of all thanks, really, thanks for your work!!
Imagino having problems to download and play games from FBA and MAME 2014.
It say that dont find the file or i must loging....
This must be a problem with the dat files...how i can update them?
Sorry for my english 😂

**Comment by langostaman** [comment]
Ok, I see the new data files from april.
I try tonight.
Thanks

**Comment by NerdFlix** [comment]
FBA links are down, Mame 2014 was already reported before. Let's be patient, IARL offers many other options

**Comment by zach-morris** [comment]
FBA should be working now.  It does for me.  MAME 2014 is already reported, and it should be resolved soon.

**Comment by langostaman** [comment]
Yes, FBA works fine yesterday.
Thanks!
