### ISSUE TITLE
Error on selecting some Atari 2600 games

### ISSUE THREAD

**Issue by NerdFlix** [zach-morris/plugin.program.iarl#48]
Hi Zach, thanks for your great addon.

I'm using the latest xmls and some games of Atari 2600(I think 3 of them) are raising errors when you select them, I saw the logs and what is causing the error is the size of them in XML assigned to "None", for example the game Pac-man(Atari 2600). The line below in xml:

<rom name="MESS_0.149_Software_List_ROMs/MESS_0.149_Software_List_ROMs.zip/MESS%200.149%20Software%20List%20ROMs%2Fa2600%2Fpacman.zip" **size="None"** />

I didn't verify other xmls, just Atari 2600.

Thanks in advance.

**Comment by zach-morris** [comment]
Thanks for the report.  I can recreate this error and I'll try to resolve it.

**Comment by NerdFlix** [comment]
I think maybe I may have resolved it, I've changed the None value to an integer, but after that IARL cache(the one cache that has games list from xml) has to be cleared or the error will happen again

**Comment by NerdFlix** [comment]
Yeah I can confirm everything is working now, thanks for the fix Zach :)

**Comment by zach-morris** [comment]
Good deal, thanks for all the testing!
