### ISSUE TITLE
Default download path?

### ISSUE THREAD

**Issue by pablinho1023** [zach-morris/plugin.program.iarl#49]
Hi! Im trying to make dreamcast work on te rpi, i cant seem to find a way to so i decided to download a dreamcast game and try to load it directly from retroarch, te thing is that theres no dreamcast folder in the rom folder so i dont know where it Was donwloaded, any idea?

**Comment by zach-morris** [comment]
https://github.com/zach-morris/plugin.program.iarl/wiki/5.--FAQ#2-where-are-the-games-downloaded-to

**Comment by pablinho1023** [comment]
So its the same to lauch a game or download it?  Its possible to play the dreamcast games?
