### ISSUE TITLE
Automatic way to generate XML files?

### ISSUE THREAD

**Issue by ginonott** [zach-morris/plugin.program.iarl#50]
Hi,

I would like to generate an XML file for ps2 and gamecube. Do you have a script written to do so from an internet archive collection or do I have to make a one off script to do this task?

Thanks

**Comment by zach-morris** [comment]
Yeah, I do not have any tools to generate lists to provide to the general user.  The tools I use to generate the lists in my addon are all homegrown, not documented, and definitely not user friendly.
