### ISSUE TITLE
Retroarch new cores list update (enhancement)

### ISSUE THREAD

**Issue by NerdFlix** [zach-morris/plugin.program.iarl#51]
Hi Zach,
There are new retroarch cores on the block hahaha(yes they're not perfect yet, but useful), can you please update their list in IARL?, for instance, they released a new core for emulator X68000 and mame is not handling some games of this platform anymore(crashing sometimes).

Thanks in advance.
New cores: https://www.libretro.com/index.php/new-core-px68k-androidioswindowslinuxmac/
https://www.libretro.com/index.php/retroarch-1-6-0-released/

**Comment by zach-morris** [comment]
I'll take a look.  I wasn't able to get this to work right when it came out.

**Comment by NerdFlix** [comment]
Yeah it is pretty buggy now

**Comment by zach-morris** [comment]
All cores listed are current / accurate as of 1.6.7
Also added an extras section, so if someone put together a reasonably working X68000 game list it can be added.  I'll call this one closed
