### ISSUE TITLE
MS-DOS offline mode: errors after initial unzip

### ISSUE THREAD

**Issue by myuubie** [zach-morris/plugin.program.iarl#55]
Hi there,

My MS-DOS archive is currently set to a different download path. Games would successfully run the first time, but subsequent runs result in an unzip/conversion error:

`:18:49.782 T:140112574035712  NOTICE: IARL:  Download started for Wolfenstein 3D
23:18:49.783 T:140112574035712   DEBUG: /home/xxx/dosbox-cdrive/Wolfenstein_3D_1992.zip
23:18:49.783 T:140112574035712   DEBUG: IARL:  Looking for matches for /home/xxx/dosbox-cdrive/Wolfenstein_3D_1992.zip - Exact Matching: False
23:18:49.788 T:140112574035712   DEBUG: IARL:  Matching files found for /home/xxx/dosbox-cdrive/Wolfenstein_3D_1992.zip: /home/xxx/dosbox-cdrive/Wolf3D/Wolfenstein 3D (1992).ba1
23:18:49.788 T:140112574035712   DEBUG: IARL:  Exact match not found.
23:18:49.788 T:140112574035712   DEBUG: IARL:  Best match /home/xxx/dosbox-cdrive/Wolfenstein_3D_1992.zip: /home/xxx/dosbox-cdrive/Wolf3D/Wolfenstein 3D (1992).ba1
23:18:49.788 T:140112574035712   DEBUG: IARL:  File was found to exist locally, no overwrite option selected
23:18:49.788 T:140112574035712   DEBUG: IARL:  Matching file that already exists: /home/xxx/dosbox-cdrive/Wolf3D/Wolfenstein 3D (1992).ba1
cdrive/Wolf3D/Wolfenstein 3D (1992).ba1
23:18:49.788 T:140112574035712   ERROR: IARL:  There was an error unzipping files for /home/xxx/dosbox-cdrive/Wolf3D/Wolfenstein 3D (1992).ba1
23:18:49.788 T:140112574035712   ERROR: IARL:  There was an error converting DOSBox files for Wolfenstein 3D
23:18:49.790 T:140112574035712   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: expected a string or other character buffer object
                                            Traceback (most recent call last):
                                              File "/home/xxx/.kodi/addons/plugin.program.iarl/addon.py", line 1901, in onClick
                                                download_and_launch_rom(self,iarl_data)
                                              File "/home/xxx/.kodi/addons/plugin.program.iarl/addon.py", line 1637, in download_and_launch_rom
                                                current_external_command = replace_external_launch_variables(iarl_data) #Function replaces command line variables
                                              File "/home/xxx/.kodi/addons/plugin.program.iarl/resources/lib/util.py", line 847, in replace_external_launch_variables
                                                command_out = command_out.replace('%ROM_PATH%',iarl_data['current_save_data']['launch_filename']) #Replace ROM filepath
                                            TypeError: expected a string or other character buffer object
                                            -->End of Python script error report<--`

The few games I tried all had this ba1 file with the same name as the zip file. So it would try to unzip this file and fail, thus not successfully providing a launch_filename to run. Currently working around this in unzip_dosbox_file by ignoring the unzip results and determining if the emu_command file already exists to return success and the full path to the command. Hope you can add a similar or better fix. :)

Thanks!

Other details: Ubuntu 17.04, Kodi 17.5. Using external dosbox launch command.

**Comment by zach-morris** [comment]
Thanks for the report, i'll take a look at this
