### ISSUE TITLE
Problem with direcory paths and Retroarch binary on LibreElec

### ISSUE THREAD

**Issue by wonder75** [zach-morris/plugin.program.iarl#57]
Hey,
sweet idea for an addon! I tried pretty hard to make it work for a few hours but failed miserably.

I am not using the special version of LibreElec, just the latest standard release version.
I followed your guide to setup IARL and Retroarch.

While debugging i realized two problems:

1. IARl doesn't detect the correct "core" path for Retroarch in util.py
In a standard LibreElec installtion the path is:
/storage/.kodi/userdata/addon_data/game.retroarch/cores

I was able to get around this problem by manualy adding the path to util.py

2. Where i got completely lost was on finding out which binary or script to pass to IARL for the Retroarch application. My retroarch app directory got these executable files:

-rwxr-xr-x    1 root     root           548 Nov 14 21:56 addon.sh
-rwxr-xr-x    1 root     root          7827 Nov 14 21:56 addon.start
-rwxr-xr-x    1 root     root      17114368 Nov 14 21:56 game.retroarch-Gen
-rwxr-xr-x    1 root     root      13725676 Nov 14 21:56 game.retroarch-RPi

I tried all of them, but wasn't able to make IARL launch Retroarch.
Results were

- nothing - after launching a ROM it just jumped back to the gamelist
- crash     - screen went black and i had to reboot my Pi
- endless loading - saw the "loading circle", waited a few minutes and gave up.

When launching Retroarch manualy it runs and I can run ROMS from inside RA.

Could you point me to the correct apppath?

Thanks!

**Comment by zach-morris** [comment]
Are you using gamestarter?  There's an option for that in 'System Type' which just points to the gamestarter scripts to launch

**Comment by wonder75** [comment]
HI, I am unsure if I do. 
I use the "gamestarter Repo" from here: https://github.com/bite-your-idols/Gamestarter
and installed Retroarch and IARL from it.

Did you mean if I use that repo or is there an actual app called "gamestarter"?

**Comment by zach-morris** [comment]
Yes, that is the addon called Gamestarter, which contains the retroarch binary and launcher scripts.  No additional configuration should be needed beyond selecting "Gamestarter Addon" for the setting "My System Type".  That language for the name of the setting is a little confusing I agree

**Comment by wonder75** [comment]
Hey thanks.
I followed your tutorial but somehow missed to understand the gamestarter part, as I am new to emulation on Pi. It works now. Thanks a lot!

**Comment by zach-morris** [comment]
Good deal.  If you think updates to the tutorial would help others please let me know what changes would make it clearer
