### ISSUE TITLE
Cleaner lists?

### ISSUE THREAD

**Issue by 83RL** [zach-morris/plugin.program.iarl#58]
I been quite a bit through the iarl code but i have no clue how the list filtering works.
i have lists with just US games that i filtered using a nifty little expression in notepad ++.

expression is:

(?-s)^\s*<game(?=.*\(Japan\))(?s).*?</game>\R

for example will remove over 1700 Japan games from snes list in 10 seconds without error.

maybe open up possibility of adding Family Computer / Super famicom as own independent systems?

like i said i dont know how the filtering works so your call.   if something that interests you and expression helps with filtering then sweet, or if you would like i could clean up lists and submit.   

im still quite noobish when it comes to github and how all this works tbh/obviously, lol.
but if you want you can set me to the task, just tell me how you want them.
your call.   dropping in snes list i just cleaned.

**Comment by 83RL** [comment]
[SNES_ZachMorris_Full.usa.zip](https://github.com/zach-morris/plugin.program.iarl/files/1503853/SNES_ZachMorris_Full.usa.zip)

**Comment by zach-morris** [comment]
This should be an option with the next IARL update.  I plan on including an 'extras' section in the addon, so users can download additional lists that aren't included by default.
See [here](https://github.com/zach-morris/iarl.extras)

**Comment by zach-morris** [comment]
We'll call this complete with the addition of Extras in 1.6.7

**Comment by 83RL** [comment]
thats awesome!  ill def contribute.

oh yea,  idk how i botched above expression, lol.



(?-s)^\s*<game(?=.*\(Japan\))(?s).*?</game>\R

Correct expression ^
