### ISSUE TITLE
"Feature" request: Allow usage from read-only installation (!=userdata) directory

### ISSUE THREAD

**Issue by amazari** [zach-morris/plugin.program.iarl#60]
Hi,
In a quest to automatize Kodi and addons deployment using Nix/NixOS [1], I stumbled upon a showstopper with IARL:
In a NixOS environment, installation directories are by nature read-only. Programs are supposed to store their state in user home only. IABT behaves mostly sanely but for one exception in resources/lib/util.py#L661 where it deletes xml files from its installation dir.

Would you consider avoiding this deletion ?
Thanks,
Alexandre

[1] https://nixos.org/

**Comment by zach-morris** [comment]
Yeah, this should be easy.  Does the addon just currently create a general python error at that point?  I could just make it a 'try' statement and if it doesn't work include a log message stating that the file was still present.

The only sane reason the files are deleted is to save space, but it wouldn't really hurt anything if they remained, as they'd be overwritten anyway if the addon were updated.  The only other downside is the addon will compare the two files every time it's used, but assuming the computer is not a potato, I'm guessing most people wouldn't even notice the startup time slowed a little.

**Comment by amazari** [comment]
Hey Zack,

Thanks for looking into this and for the patch.

>  Does the addon just currently create a general python error at that point? I could just make it a 'try' statement and if it doesn't work include a log message stating that the file was still present.

Python does raise an exception and catching it early solves my issue. Thanks! Still ... 

> The only sane reason the files are deleted is to save space, but it wouldn't really hurt anything if they remained, as they'd be overwritten anyway if the addon were updated. The only other downside is the addon will compare the two files (userdata and addondata) every time it's used, but assuming the computer is not a potato, I'm guessing most people wouldn't even notice the startup time slowed a little.

... it is not entirely clear what is the purpose of the copy + comparison here. Those files are AFAICS games metadata that are not supposed to change often. Are the copies supposed to be modified by the user and/or the addon ?
If I understand well, they are overwritten by the latest version anyway, so why have a userdata copy instead of directly reading the systemwide version ?
Not that it matter for this issue but just curious !

> How does the system install the addon in the first place if it's read only?

The addon is not installed using Kodi's facilities but the NixOS system generator. It takes a system description (example at [1]) and turns it into a runnable system (on vm or real hw).

I am working on making kodi's deployment declarative in this context too. So one might have for example:
`
service.kodi.plugins = [iarl, youtube, advanced-emulator-launcher];
`
Invoking the system generator would get the plugins somehow and copies them at the right place.
Once the system is build following the recipe, the filesystem is basically turned read-only.
This is a great simplification of NixOs, which I would definitely advice you to take a look at. It is worth it :)

[1] https://gist.github.com/Kendos-Kenlen/5c75cbe7fb1377138ab77383d83db668

**Comment by zach-morris** [comment]
> ... it is not entirely clear what is the purpose of the copy + comparison here.

Here's what that code is for:
When the IARL addon is installed, the xml files need to live in the userdata folder, so on the first install, the data is copied to userdata/dat_files.

If IARL is updated at a later point, then the addon will again have xml files in the addon folder.  It will compare files with the same filename between addondata and userdata.  If two files have the same filename but different version numbers, then it will prompt the user on what to do (either overwrite userdata, or ignore the update, or decide later).  This is done in case an xml file is updated, like if the URL changes.  The XML files are not expected to change often, but you can see by my commits that they do from time to time.

The only downside to this failure to delete the files is that the comparison is done every time the addon is run.  If they're the same, then the user is never prompted.  If they are different, the user is prompted on what to do.  There will be a problem if the file cannot be deleted and it is updated.  The user will get a prompt every time they start the addon on the different xml file versions if they decide not to update.
