### ISSUE TITLE
Add-on always downloads ROM

### ISSUE THREAD

**Issue by drinfernoo** [zach-morris/plugin.program.iarl#62]
I've checked the option to not download again of a ROM is already present, but it looks like it downloads every single time I pick a game, even if I've already downloaded it.

**Comment by zach-morris** [comment]
Set the addon cache to something non-zero.  Zero cache = download every time (even if it's the same game)

**Comment by zach-morris** [comment]
I've updated the [FAQ](https://github.com/zach-morris/plugin.program.iarl/wiki/5.--FAQ#2-where-are-the-games-downloaded-to) to try and make this as clear as possible.  I'll consider this closed.
