### ISSUE TITLE
Remove/avoid duplicates in Last Played?

### ISSUE THREAD

**Issue by drinfernoo** [zach-morris/plugin.program.iarl#67]
I'm wondering if there's a possibility to keep games from duplicating in Last Played. It keeps ten games in the list (by default), but if they're all the same game, that's not very helpful.

**Comment by zach-morris** [comment]
Good idea, thanks for opening the issue.

**Comment by drinfernoo** [comment]
No problem. If I can help in any way, let me know.

**Comment by zach-morris** [comment]
Fixed in 1.6.9
