### ISSUE TITLE
Save States not working for NES or MAME

### ISSUE THREAD

**Issue by mattogrady87** [zach-morris/plugin.program.iarl#69]
Save States work when playing but if I exit RetroArch and load the same game again from IARL it loads the save state but starts at beginning of game.

Save states are working for locally stored files for me.

Side note: If I select download from within IARL where does that file go? I'm on ARch/Linux, can't seem to find them locally. Thanks for looking, sorry if I'm missing any details. Also, great idea and job on this plugin!

**Comment by zach-morris** [comment]
IARL doesn't do anything with regard to save states.  It just launches the game.  I recommend heading over to the libretro forum for to find a solution.  Personally, I have hotkeys setup for load and save states and after i launch a game, I just hit the load save hotkey and that works.

See [here](https://github.com/zach-morris/plugin.program.iarl/wiki/5.--FAQ#2-where-are-the-games-downloaded-to) for the 2nd question
