### ISSUE TITLE
Default cores launched by RetroArch using IARL

### ISSUE THREAD

**Issue by ChEvRi1979** [zach-morris/plugin.program.iarl#72]
I'm a bit new to IARL and RetroArch, so my bad if this is a stupid question or the wrong place to ask...

Is there a list somewhere of the default cores IARL is set to use when launching ROMS in RetroArch?  I would like to reset everything back to default.  Restoring the default settings in IARL didn't work.  Even uninstalling and reinstalling the add-on in Kodi didn't seem to work.

Is this controlled in IARL or in RetroArch itself?  I didn't find anything obvious in the retroarch.cfg file that controls this, so I assume IARL has a config somewhere that chooses which core is launched under which system.  I'll be happy to manually go through and reset the cores launched under each supported system if I can get the list, but if there's a config file I can delete or edit or something, that would be great too.

Thanks in advance!

**Comment by zach-morris** [comment]
The launch settings are saved in the game list xml files.  You can view the settings for a list by highlighting it, bringing up the context menu, and selecting "Review Launch Command".

You have a few options:
You can just re-run the wizard (see step 4 [here](https://github.com/zach-morris/plugin.program.iarl/wiki/1.--Setup#basic-setup-instructions)), and that will set all the cores to a default

Or, you can manually set a core for each game list (see steps [here](https://github.com/zach-morris/plugin.program.iarl/wiki/1.--Setup#-))

**Comment by ChEvRi1979** [comment]
Thanks.  Running the wizard again set everything to default, so I'm going in and making a manual list of all of the default cores each system uses.  That way if something gets out of whack again, I don't have to reset the whole thing.

Part of the reason my build may have gotten a little messed up is because in IARL, when you bring up the context menu on a system and choose "Update Ext Launcher Command"; if you pick the wrong launcher and then hit the "Cancel" button on the far right of the menu that asks if you are sure, it updates to that launcher anyway.  That may be something you can fix in a future build.  I know to avoid it now and use the OTHER "Cancel" button, but still...could be an issue for someone else down the road.

**Comment by zach-morris** [comment]
Thanks for the report, I can fix that in the next update

**Comment by ChEvRi1979** [comment]
For anyone needing to know, here is the current default list:

 - 3DO - RetroArch 4DO (4DO) (4do_libretro.dll)
 - Amiga - RetroArch FSUAE (Amiga) (FS_UAE)
 - Amiga CD32 - RetroArch FSUAE (Amiga) (FS_UAE)
 - Apple 2GS - RetroArch MESS 2014 (MESS 0.159) (mess2014_libretro.dll)
 - Atari 800 - RetroArch MESS 2014 (MESS 0.159) (mess2014_libretro.dll)
 - Atari2600 - RetroArch Stella (Atari 2600) (stella_libretro.dll)
 - Atari 5200 - RetroArch MESS 2014 (MESS 0.159) (mess2014_libretro.dll)
 - Atari 7800 - RetroArch ProSystem (Atari 7800) (prosystem_libretro.dll)
 - Atari Jaguar - RetroArch Virtual Jaguar (Jaguar) (virtualjaguar.libretro.dll)
 - Atari Lynx - RetroArch Handy (Lynx) (handy_libretro.dll)
 - Atari ST - RetroArch Hatari (Atari ST/STE/TT/Falcon) (hatari_libretro.dll)
 - CaveStory - RetroArch CaveStory (NXEngine) (nxengine_libretro.dll)
 - ColecoVision - RetroArch BlueMSX (MSX) (bluemsx_libretro.dll)
 - Commodore 64 - RetroArch VICE C64 (C64) (vice_x64_libretro.dll)
 - Dinothawr - RetroArch Dinothawr (Standalone Game) (dinothawr_libretro.dll)
 - Doom - RetroArch PrBoom (Doom) (prboom_libretro.dll)
 - EasyRPG - RetroArch EasyRPG (RPG Maker 2000/2003) (easyrpg_libretro.dll)
 - Final Burn Alpha - RetroArch FBA (Arcade Latest) (fbalpha_libretro.dll)
 - Game and Watch - RetroArch Game and Watch (Game and Watch) (gw_libretro.dll)
 - Game Boy Advance - RetroArch mGBA (GBA) (mgba_libretro.dll)
 - Game Boy Classic - RetroArch Gambatte (GB/GBC) (gambatte_libretro.dll)
 - Game Boy Color - RetroArch Gambatte (GB/GBC) (gambatte_libretro.dll)
 - Game Gear - RetroArch Genesis Plus GX (GG/SMS/Gen/PICO/SG-1000) (genesis_plus_gx_libretro.dll)
 - Intellivision - RetroArch MESS 2014 (MESS 0.159) (mess2014_libretro.dll)
 - Lutro - RetroArch Lua Engine (Lutro) (lutro_libretro.dll)
 - Magnavox Odyssey 2 - RetroArch 02EM (Odyssey2/Videopac) (o2em_libretro.dll)
 - MAME - 2003 - RetroArch MAME 2003 (Arcade 0.78) (mame2003_libretro.dll)
 - MAME - Multiple Arcade Machine Emulator - RetroArch MAME (Arcade Latest) (mame_libretro.dll)
 - Master System - RetroArch Genesis Plus GX (GG/SMS/Gen/PICO/SG-1000) (genesis_plus_gx_libretro.dll)
 - MS-DOS Games - RetroArch DOSBox (DOS) (dosbox_libretro.dll)
 - MSX1 - None
 - MSX2 - None
 - NEC - PC Engine - TurbroGrafx 16 - RetroArch Mednafen PCE FAST (PCE/TG16) (mednafen_pce_fast_libretro.dll)
 - Neo Geo CD - RetroArch MESS 2014 (MESS 0.159) (mess2014_libretro.dll)
 - Neo Geo Pocket Color - NGPC - RetroArch Mednafen NeoPop (NG/NGPC) (mednafen_ngp_libretro.dll)
 - Nintendo 64 - N64 - RetroArch ParaLLEl (N64) (parallel_n64_libretro.dll)
 - Nintendo Entertainment System - NES - RetroArch Nestopia (NES) (nestopia_libretro.dll)
 - Nintendo Virtual Boy - RetroArch Mednafen VB (VirtualBoy) (mednafen_vb_libretro.dll)
 - PCE CD - RetroArch Mednafen PCE FAST (PCE/TG16) (mednafen_pce_fast_libretro.dll)
 - Phillips CD-i - RetroArch MESS 2014 (MESS 0.159) (mess2014_libretro.dll)
 - Playstation - RetroArch Mednafen PSX (PS1) (mednafen_psx_libretro.dll)
 - Quake - RetroArch TyrQuake (Quake) (tyrquake_libretro.dll)
 - Scumm VM - RetroArch ScummVM (Various) (scummvm_libretro.dll)
 - Sega 32X - RetroArch PicoDrive (SMS/Gen/Sega CD/32X) (picodrive_libretro.dll)
 - Sega CD - RetroArch PicoDrive (SMS/Gen/Sega CD/32X) (picodrive_libretro.dll)
 - Sega Dreamcast - RetroArch Reicast (Dreamcast) (reicast_libretro.dll)
 - Sega Genesis - RetroArch Genesis Plus GX (GG/SMS/Gen/PICO/SG-1000) (genesis_plus_gx_libretro.dll)
 - Sega Saturn - RetroArch Mednafen Saturn (Saturn) (mednafen_saturn_libretro.dll)
 - Sega SG-1000 - RetroArch Genesis Plus GX (GG/SMS/Gen/PICO/SG-1000) (genesis_plus_gx_libretro.dll)
 - Super Nintendo Entertainment System - SNES - RetroArch SNES9x (SNES Latest) (snes9x_libretro.dll)
 - Vectrex - RetroArch VECX (Vectrex) (vecx_libretro.dll)
 - Windows 3.x Games - RetroArch DOSBox (DOS) (dosbox_libretro.dll)
 - Wonderswan - RetroArch Mednafen Cygne (WonderSwan/WonderSwan Color) (mednafen_wswan_libretro.dll)
 - Wonderswan Color - RetroArch Mednafen Cygne (WonderSwan/WonderSwan Color) (mednafen_wswan_libretro.dll)
 - x68000 - RetroArch MESS 2014 (MESS 0.159) (mess2014_libretro.dll)
 - ZX Spectrum - RetroArch FUSE (Spectrum) (fuse_libretro.dll)
