### ISSUE TITLE
Issue with release dates on game launch pages

### ISSUE THREAD

**Issue by ChEvRi1979** [zach-morris/plugin.program.iarl#75]
I'm editing/building some libraries, and I noticed a few issues with the release dates displaying at the top right on a game's launch page.

First, I've realized while editing the dat files that the < releasedate > format needs to be "DD/MM/YYYY", even though it displays on the game's page as "MM/DD/YYYY".  The Atari 7800 list I'm currently editing (Atari_7800_ZachMorris.xml) has the dates in "MM/DD/YYYY" format, so they are displaying incorrectly.  That may not be so much an issue as an annoyance, but I thought it was worth bringing up if you can address it and fix it.

The second issue I'm having is, in some instances, I can't get the date to display at all.  For example, as I said, I'm editing the Atari 7800 dat file (Atari_7800_ZachMorris.xml).  Under the information for Pete Rose Baseball, you'll find < releasedate >05/27/1989< /releasedate >.  As I mentioned, that's backwards, and should be < releasedate >27/05/1989< /releasedate > in order to display correctly.  The problem is, it won't display either way.  HOWEVER, if you change it to something like < releasedate >07/05/1989< /releasedate > and refresh the archive, it will suddenly display.  I can't for the life of me understand why having the day as "07" will display, but if it's changed to "27", it will not.  Any ideas?

What I'd recommend, if you can, is just have the date display exactly as written.  It'd be really nice for titles that only the launch year is available!

**Comment by zach-morris** [comment]
Yeah, the dates are confusing for sure - I have absolutely struggled to get that to work in the past.  The main issue is all sources for game / rom information have different formats.  From the documentation, as I understand it, Kodi is looking for the format DD/MM/YYYY.

My addon uses [dateutil](https://github.com/zach-morris/plugin.program.iarl/blob/master/resources/lib/util.py#L10) to try and normalize the dates to the correct format.  The dates listed in the dat files are typically directly from whatever source I've scraped them from.  That being said, the easiest thing to do is just update the dat file in my addon to resolve the problem.  I'll take a look at the Atari 7800 dat file and see if I can understand what it doesn't like.  If there are other area's you find issues you can post them here and I'll take a look.

**Comment by ChEvRi1979** [comment]
I am working on cleaning up ALL of the dat files with good box art, nice screen shots, full game descriptions and info, and removed duplicates.  It's going to take a while because I'm just going in and doing it all by hand, but once I finish, I'll upload them for everyone.

**Comment by zach-morris** [comment]
By hand would be pretty painful...  I'd say almost 100% of the info in the dat files was scripted

**Comment by zach-morris** [comment]
By hand would be pretty painful...  I commend you for attempting it.  I'm working on another project for the dat files as sort of a standalone resource (for other scrapers and systems to use as they please), so if you come up with some good updates please push them.
