### ISSUE TITLE
roms wont launch on windows (solved)

### ISSUE THREAD

**Issue by camatthew** [zach-morris/plugin.program.iarl#77]
when i press open it downloads but doesent open.

**Comment by zach-morris** [comment]
Works for me.  I'd need a debug log tp know what the problem is.

**Comment by camatthew88** [comment]
i followed the setup guide. How do i get a debug log

**Comment by zach-morris** [comment]
https://kodi.wiki/view/Log_file/Easy

**Comment by camatthew** [comment]
http://paste.kodi.tv/daketoqumi

**Comment by zach-morris** [comment]
Everything seems correct from the addon.  It sends the following command to launch the game after it's downloaded:
```
"C:\RetroArch\retroarch.exe"  -L "C:\RetroArch\cores\nestopia_libretro.dll" "C:\Users\schroder79\AppData\Roaming\Kodi\userdata\addon_data\plugin.program.iarl\temp_iarl\Zelda II - The Adventure of Link (USA).nes"
```

My guess is retroarch isn't setup quite correctly.  The core isn't available is the most likely issue.  You can test this by pasting the command above into a command prompt and see what retroarch complains about.

You can also try this command for even more info:
```
"C:\RetroArch\retroarch_debug.exe"  -L "C:\RetroArch\cores\nestopia_libretro.dll" "C:\Users\schroder79\AppData\Roaming\Kodi\userdata\addon_data\plugin.program.iarl\temp_iarl\Zelda II - The Adventure of Link (USA).nes"
```

**Comment by camatthew** [comment]
It only shows a blank line

**Comment by zach-morris** [comment]
Pasting that into command prompt has to result in some response from the program.  Either an error or the program starting.

**Comment by camatthew** [comment]
Microsoft Windows [Version 10.0.17134.112]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\schroder79>"C:\RetroArch\retroarch_debug.exe"  -L "C:\RetroArch\cores\nestopia_libretro.dll" "C:\Users\schroder79\AppData\Roaming\Kodi\userdata\addon_data\plugin.program.iarl\temp_iarl\Zelda II - The Adventure of Link (USA).nes"

C:\Users\schroder79>"C:\RetroArch\retroarch.exe"  -L "C:\RetroArch\cores\nestopia_libretro.dll" "C:\Users\schroder79\AppData\Roaming\Kodi\userdata\addon_data\plugin.program.iarl\temp_iarl\Zelda II - The Adventure of Link (USA).nes"

C:\Users\schroder79>"C:\RetroArch\retroarch.exe"  -L "C:\RetroArch\cores\nestopia_libretro.dll" "C:\Users\schroder79\AppData\Roaming\Kodi\userdata\addon_data\plugin.program.iarl\temp_iarl\Zelda II - The Adventure of Link (USA).nes"

C:\Users\schroder79>"C:\RetroArch\retroarch.exe"  -L "C:\RetroArch\cores\nestopia_libretro.dll" "C:\Users\schroder79\AppData\Roaming\Kodi\userdata\addon_data\plugin.program.iarl\temp_iarl\Zelda II - The Adventure of Link (USA).nes"

C:\Users\schroder79>

**Comment by zach-morris** [comment]
Well I just pasted the same command into a command prompt.  I got an error obviously because my setup is different:
```
The system cannot find the path specified.
```

Updating the command for my system to the correct paths i get:
```
[INFO] Redirecting save file to "/Users/xxx/Documents/RetroArch/saves/1.srm".
[INFO] Redirecting savestate to "/Users/xxx/Documents/RetroArch/states/1.state".
[INFO] === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AVX2 AES 
Built: May  4 2018
[INFO] Version: 1.7.3
[INFO] =================================================
...
```

I'm not sure I can help more than this...

**Comment by camatthew** [comment]
should i move it

**Comment by camatthew** [comment]
i fixed it please close it
