### ISSUE TITLE
LibreELEC

### ISSUE THREAD

**Issue by RobLoach** [zach-morris/plugin.program.iarl#9]
Know if this'll work in LibreELEC?

**Comment by zach-morris** [comment]
It does! See the builds here with retroarch included [here](https://forum.libreelec.tv/thread-302.html).  Wiki will be updated with info for LibreELEC soon.

**Comment by trevevs** [comment]
hey  Zach
Just installed latest gamsestarter 2.5 (3 days old!) on libreelec 7 fresh build.  IARL wont install from the repo.  Says failed to install dependency- think I saw dateutil flash up.  Maybe I shd try the older ver of GS unless you have an update planned??
cheers

**Comment by zach-morris** [comment]
The dependencies should automagically be installed, although I haven't tried the latest libreelec build.  If they aren't you can manually install them from [here](http://ftp.halifax.rwth-aachen.de/xbmc/addons/krypton/), and it should work.
Dependencies required are listed in the [addon.xml](https://github.com/zach-morris/plugin.program.iarl/blob/master/addon.xml)

**Comment by trevevs** [comment]
thanks for the reply Zach.
I'm not talking about the latest alpha krypton, but the latest stable libreelec 7.0.2?  IARL hasn't been tested with 7.0.2?  All I did was install the latest fresh LE 7.0.2 on rpi3, installed gamestarter 2.5, then tried IARL and its not installing.  Am I missing something daft?  Didn't think I was doing anything out the ordinary?

**Comment by zach-morris** [comment]
If you have time you can turn on debug logging and provide the log here to determine what the issue is.  I haven't changed anything though, and IARL has installed on Kodi/LibreElec in the past with no issues, so I'm only assuming something changed in LibreElec to cause issues.

The dependencies I linked are for Kodi, and should work with LibreElec, if you wanted to install them manually (assuming thats what the problem is).

**Comment by trevevs** [comment]
wow that was freakin weird!  seems I couldnt open the official kodi repo which meant stuff wasnt up to date.  Cause: my vpn being selective over which sites it allows access to! switched my gateway to open connection and bang- everything updated!  Funny that on same VPN my OSMC Kodi repo works fine?!?  Although OSMC kodi repo ver is 9.9.9 and LE is 2.4.9.  Some weird DNS thing!
unbelievable!

**Comment by zach-morris** [comment]
Wiki updated
